#ifndef TFG_AXI_LITE_REGS_H
#define TFG_AXI_LITE_REGS_H

#define TFG_AXI_LITE_REGS_REG_ID           0x00u
#define TFG_AXI_LITE_REGS_REG_VERSION      0x04u
#define TFG_AXI_LITE_REGS_REG_CONTROL      0x08u
#define TFG_AXI_LITE_REGS_REG_STATUS       0x0Cu
#define TFG_AXI_LITE_REGS_REG_WDATA        0x10u
#define TFG_AXI_LITE_REGS_REG_RDATA        0x14u
#define TFG_AXI_LITE_REGS_REG_WRITE_COUNT  0x18u
#define TFG_AXI_LITE_REGS_REG_READ_COUNT   0x1Cu

#define TFG_AXI_LITE_REGS_ID_VALUE         0x54464700u
#define TFG_AXI_LITE_REGS_VERSION_1_0_0    0x00010000u

#define TFG_AXI_LITE_REGS_CONTROL_CLEAR_COUNTERS_MASK  0x1u

#define TFG_AXI_LITE_REGS_STATUS_READY_MASK            0x1u

#endif
